os: osx
osx_image: xcode11.3
language: swift
script:
- xcodebuild clean test -project CICD-TestProject.xcodeproj -scheme CICD-TestProject "platform=iOS Simulator,OS:13.3, name:iPhone 11 Pro"
xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone 11 Pro
